name: CI/CD

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  # CI: Continuous Integration (Testes)
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm" # cache do node_modules

      - run: npm ci # mais seguro que npm install em CI

      - run: npm run test:coverage # Jest com coverage

      - name: Upload relatório de coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/

  # Deploy no Render via Webhook
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy no Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -sS -X POST "$DEPLOY_URL"

  # deploy:
  #   needs: ci
  #   runs-on: ubuntu-latest
  #   # para deploy automático em push para main, use: if: github.ref == 'refs/heads/main'
  #   # if: startsWith(github.ref, 'refs/tags/v') # só roda deploy em tags de versão
  #   if: startsWith(github.ref, 'refs/heads/main') # roda deploy em push para main

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Deploy
  #       run: |
  #         echo "Simulando deploy..."
  #         echo "Aqui você colocaria seus comandos reais de deploy"
